### ISSUE TITLE
Codes for the different errors and warnings

### ISSUE THREAD

**Issue by Michael-Klassen** [tonyhffong/Lint.jl#106]
I want to add codes to all the errors and warnings like the python linters (e.g. [pep8](https://pep8.readthedocs.org/en/latest/intro.html#error-codes)).  
 - Make it easier to identify and differentiate between the different types of messages
 - Allow us to add an option to pass a list of messages to ignore

**Comment by Michael-Klassen** [comment]
I would also like to remove the `FATAL` error level as it is only used in the message `"cannot find include file: "` which can easily be an `ERROR`.

**Comment by Michael-Klassen** [comment]
@tonyhffong any thoughts

**Comment by tonyhffong** [comment]
Sorry for the delay. I'm ok with removing FATAL. As you say it's a bit redundant. I'm happy to have hierarchical warning types like pythons, as long as someone is willing to put in the effort to organize the universe of messages.
That said, it's not really appropriate to emphasize this feature as to make it easy to circumvent lint messages. The messages are there for a reason. So it feels kind of self-defeating to me.
