### ISSUE TITLE
Drop support for v0.3?

### ISSUE THREAD

**Issue by TotalVerb** [tonyhffong/Lint.jl#116]
There is a lot of complexity in Lint needed to handle compatibility across versions, especially because Lint piggybacks on Julia. The REQUIRE file has already mandated using v0.4 to run Lint, but there's still a lot of code being kept to allow for linting code in v0.3. Due to the nature of the parser, this is fickle, and doesn't work in a lot of circumstances.

I think it would be simpler to drop support for linting v0.3 altogether, and instruct users to use an older version of Lint if they want to lint v0.3 code.

**Comment by tonyhffong** [comment]
I agree with this. We should focus on maximizing utility to the community with the limited resources available. And that would mean the focus is to support current release and then to follow closely the development version as best as we can.

**Comment by Michael-Klassen** [comment]
+1
