### ISSUE TITLE
Read the Docs Auto Update

### ISSUE THREAD

**Issue by Michael-Klassen** [tonyhffong/Lint.jl#120]
https://read-the-docs.readthedocs.org/en/latest/webhooks.html#github

@tonyhffong

**Comment by tonyhffong** [comment]
okay. that was easy.

**Comment by tonyhffong** [comment]
btw, you have done an amazing job with the documentation. I couldn't have done this better myself.

**Comment by Michael-Klassen** [comment]
Thank you.
