### ISSUE TITLE
Error: Though valid in 0.4, ...

### ISSUE THREAD

**Issue by LouisMagarshack** [tonyhffong/Lint.jl#121]
Hi all,

I'm (only now) upgrading some modules to Julia 0.4. I would like the same code to run in a 0.4 and 0.3 kernel.

So I have things that look like:

```julia
module EmptyTestModule
  using Compat
  x = @compat UInt(2)
end
```

Is there a way to have Linting succeed with both 0.3 and 0.4?
Currently I get the following error in 0.3: "Though valid in 0.4, you want uint() instead of UInt()".

Cheers,
Louis

PS: I love Lint.jl, it's saved me quite a few headaches in the past : )

**Comment by tonyhffong** [comment]
Unfortunately, we don't consider support in 0.3 to be high priority. See this: https://github.com/tonyhffong/Lint.jl/issues/116

**Comment by Michael-Klassen** [comment]
If you want to support both 0.3 and 0.4 try using:
```julia
module EmptyTestModule
    using Compat
    if Version > v"0.4.0-dev+1830"
        x = @compat UInt(2)
    else
         x = @compat uint(2)
    end
end
```

**Comment by LouisMagarshack** [comment]
Got it, thanks for the reply! I'll keep linting my 0.4 code and trust my other unit tests for 0.3.

Cheers
