### ISSUE TITLE
Does not work with -e

### ISSUE THREAD

**Issue by SanketDG** [tonyhffong/Lint.jl#144]
When I run a command:

```
julia -e 'import Lint.lintfile; lintfile("/home/sanket/coala-bears/bad.jl")'
```
there is no output

but when I do
```
julia -E 'import Lint.lintfile; lintfile("/home/sanket/coala-bears/bad.jl")'
```
there is
```
LintResult([/home/sanket/coala-bears/bad.jl:1 E321 hello: use of undeclared symbol])
```

The first command used to work previously, so I am guessing there has been change.

**Comment by TotalVerb** [comment]
Yes, there has been change. You might need to do `display(lintfile("file"))` now.

**Comment by Michael-Klassen** [comment]
`Lint` no longer prints the output to `STDOUT`. #138 replaced `returnMsgs` keyword argument with a `LintResult` type that is always returned, but displays well in multi-line. You could add a `println` to your `-e` command:
```julia
julia -e 'import Lint.lintfile; println(lintfile("/home/sanket/coala-bears/bad.jl"))'
```

**Comment by SanketDG** [comment]
@Michael-Klassen thanks, but I need just the output. I will use @TotalVerb's solution. :smile:
