### ISSUE TITLE
The linter is hanging

### ISSUE THREAD

**Issue by meowklaski** [tonyhffong/Lint.jl#170]
Running Julia 0.5 on Windows 10, `lintfile` hangs on a `.jl` file with the following contents:

```julia
y = x +1
0 = 1
```

**Comment by TotalVerb** [comment]
Thanks for the report. I am unable to reproduce the issue. Are you sure you have attached the entire contents of the file that files to lint?

**Comment by TotalVerb** [comment]
The output I get is

```julia
julia> lintfile("test.jl")
test.jl:1 E321 x: use of undeclared symbol
test.jl:2 I171 0: LHS in assignment not understood by Lint
```

which seems as expected.

**Comment by meowklaski** [comment]
Yes, that was the full contents of the file

**Comment by TotalVerb** [comment]
Are you able to reproduce this from the REPL?

**Comment by TeroFrondelius** [comment]
The linter is hanging on Windows for me. This happens both versions 0.2.5 as well as latest master. 

```julia
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: NT (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

To reproduce (on Windows):
```julia
julia> using Lint

julia> str2 = """
              test = "a"
              kj
              """;

julia> msgs2 = lintfile("file", str2)
```

I have been debugging linter-julia and it took full day to narrow the problem down to above example (mostly because I was looking the bug in the wrong place). Cross reference https://github.com/TeroFrondelius/linter-julia/issues/16

**Comment by TeroFrondelius** [comment]
I switched to linux:
```julia
julia> str2 = """
              test = "a"
              kj
              """;

julia> msgs2 = lintfile("file", str2)
file:2 E321 kj: use of undeclared symbol
```
No problem.
