### ISSUE TITLE
Drop 0.4 support?

### ISSUE THREAD

**Issue by TotalVerb** [tonyhffong/Lint.jl#174]
It is a real pain to support three versions of Julia simultaneously. With #172 bringing 0.6 support, and 1.0 anticipated for release this year, I think our limited resources should be focused on 0.5 and future releases.

**Comment by TeroFrondelius** [comment]
I'm supporting this. In my opinion, the current released version of Lint.jl is good enough for julia 0.4 users.

**Comment by Michael-Klassen** [comment]
I'm fine with dropping support for 0.4.
