### ISSUE TITLE
Default or Globally Declared Ignored Variable Names

### ISSUE THREAD

**Issue by cortner** [tonyhffong/Lint.jl#189]
I often find myself writing  things like 
```
result = [f(a)  for  (a, _1, _2, _3) in someiterator]
```

While `Lint` ignores `_`, there is no other ignored symbol. so I get results such as 
```
lintstr("""
       [z for (z, _, _2) in zip(rand(10), 1:10, zeros(10))]
       """)
1-element Array{Lint.LintMessage,1}:
 none:1 W341 __: local variable declared but not used
```
I can of course use `@lintpragma`, but this happens far too often, and it is sometimes 3 or more variables in a one-line piece of code that need to be ignored. 

I therefore wonder whether there could be a longer list of ignored symbols?

**Comment by TotalVerb** [comment]
https://github.com/tonyhffong/Lint.jl/pull/213 addresses this particular problem. Even more configurability of ignored declared variable names would be nice.
