### ISSUE TITLE
Add name of undeclared symbol in `E321`

### ISSUE THREAD

**Issue by dpsanders** [tonyhffong/Lint.jl#190]
It would be useful to have the undeclared symbol(s) listed in the `E321` error message.

**Comment by TeroFrondelius** [comment]
Hi @dpsanders, 
This is actually linter-julia bug:
```julia
julia> using Lint

julia> lintfile("fileName.jl","THIS_IS_SHOWN")
fileName.jl:1 E321 THIS_IS_SHOWN: use of undeclared symbol


julia>
```

**Comment by TeroFrondelius** [comment]
I opened a new issue to track this. https://github.com/TeroFrondelius/linter-julia/issues/29

**Comment by TeroFrondelius** [comment]
This is fixed in liner-julia. This issue can be closed.

**Comment by dpsanders** [comment]
Thanks!
