### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by dpsanders** [tonyhffong/Lint.jl#191]
For use with the `linter-julia` Atom plugin.

**Comment by TeroFrondelius** [comment]
I want to have this Windows fix https://github.com/tonyhffong/Lint.jl/pull/188, merged before new tag. Although, it's already checked and ready to merge.

**Comment by TeroFrondelius** [comment]
For me it would make sense to add #194 before tagging a new version. I would also like to see #179 and #184 get merged for the next release. What do you think @TotalVerb, @Michael-Klassen and @tonyhffong?

**Comment by dpsanders** [comment]
Releases are cheap...

**Comment by TotalVerb** [comment]
We need to first merge #194 before tagging, as that includes an important change to REQUIRE.

**Comment by TeroFrondelius** [comment]
I'm supporting the idea of attobot. I have used it one time and it made the registration to METADATA really easy. Even committing changes to the pull request was easy, you just need to delete both the release and the tag separately and then recreate the release in Github.

**Comment by TotalVerb** [comment]
Attobot definitely makes this easier, but since Tony is the owner of this repository, he is the only one who can enable it.
