### ISSUE TITLE
Linter errors on Plots recipes

### ISSUE THREAD

**Issue by mkborregaard** [tonyhffong/Lint.jl#192]
The Plots.jl ecosystem is heavily dependent on a domain-specific syntax, named as 'recipes'. The basic syntax of recipes (https://juliaplots.github.io/recipes/) is flagged as an error by Lint. Here is an MWE with working code:

<img width="580" alt="skaermbillede 2017-02-19 kl 22 52 43" src="https://cloud.githubusercontent.com/assets/8429802/23107010/3cd21772-f6f6-11e6-80e9-ae8aedf4a5f9.png">

**Comment by TotalVerb** [comment]
I think the best solution to this is to ignore linting whatever is in `@recipe`. Does this introduce a symbol `f` that can be used in the surrounding scope? If so we can ignore everything except for any introduced names.

**Comment by mkborregaard** [comment]
No, the name `f` is discarded by `@recipe`. The special symbols `-->` and `:=` can have as left side only a small number of names (it should be easy to make a table), each of these can be matched by only certain Types on the right hand side. I or someone else could supply these, in order to make a more functional parsing of these? 
Let me just ping @tbreloff who is the inventor and maintainer of the syntax.

**Comment by TotalVerb** [comment]
A future goal for Lint would be to make it more modular and hence make this kind of specialized linting for DSLs more practical; but for right now I'd like to avoid the increase in complexity.

The short term solution, then, would be to simply not lint the `@recipe` macro. I'll try to get a system for ignoring certain macros implemented in the coming week.

**Comment by tbreloff** [comment]
Agreed skipping recipes is the way to go.

**Comment by mkborregaard** [comment]
@TotalVerb absolutely, that makes sense. That is why I asked about domain-specific syntaxes on discourse :-) Sounds like a very cool future goal, though.
