### ISSUE TITLE
Spurious "assigning an error to a variable"

### ISSUE THREAD

**Issue by KristofferC** [tonyhffong/Lint.jl#209]
```jl
julia> lintstr("""
       function f{N}(::N)
           for j in 1:N
           end
       end
       """)
1-element Array{Lint.LintMessage,1}:
 none:2 E539 j: assigning an error to a variable
```

**Comment by TotalVerb** [comment]
This particular case seems fine to me because `N` has to be a type. I suppose the original code had N as a dimension type parameter though?

**Comment by KristofferC** [comment]
I reduced the example too much but yes, originally it was a dimension type of parameter.
