### ISSUE TITLE
"w-" prevents the linter from linting the rest of the file

### ISSUE THREAD

**Issue by gdkrmr** [tonyhffong/Lint.jl#238]
Tested in emacs and atom:

![screenshot from 2017-07-28 11-08-14](https://user-images.githubusercontent.com/12512930/28710721-6c6f2be4-7385-11e7-9f25-8d295a8352a2.png)

**Comment by gdkrmr** [comment]
if `w -` is on a line itself, it works fine

**Comment by TotalVerb** [comment]
This is a syntax error, isn't it?

**Comment by gdkrmr** [comment]
this is a feature ;-)
