### ISSUE TITLE
guesstype on array function is a rabbit-hole

### ISSUE THREAD

**Issue by tonyhffong** [tonyhffong/Lint.jl#27]
The current guesstype() is a bit ad hoc on treating the rich collection of array functions. There are many tricky bits like hcat, vcat on arrays arguments.

I don't usually work on higher dimensional arrays all that often, so progress is a bit stop-and-go. Just throw it out there. Someone who breathes these things can probably guide or even lead our effort. It'd be nice if we can lint code based on information about the element type and the dimension count.

**Comment by TotalVerb** [comment]
This has generally been fixed by #184.
