### ISSUE TITLE
Undeclared argument warning only for one argument?

### ISSUE THREAD

**Issue by nilshg** [tonyhffong/Lint.jl#62]
The following function:
````
function f(x1, x2, x3)
  x1 
end
````
will create an info saying that `x2` is unused, but not that `x3` is unused as well. It appears that only one warning per function is produced, independent of the number of unused declared arguments?
(Of course this is not the worst issue as one usually would run lintfile again after clearing out the first unused arguments, which would create an info for the next one.)

**Comment by tonyhffong** [comment]
Sorry for taking so long to fix it. I've been looking at the wrong place the whole time.
