### ISSUE TITLE
Available SublimeLinter plugin

### ISSUE THREAD

**Issue by tomaskrehlik** [tonyhffong/Lint.jl#74]
I have turned my previous gist into a normal plugin. Maybe if you wanted to reference it on README, might be useful. If you have any suggestions, they would be welcome. Thanks for the package!

**Comment by tonyhffong** [comment]
Could you post the link to me? I couldn't find it.

**Comment by tomaskrehlik** [comment]
sorry.

https://github.com/tomaskrehlik/SublimeLinter-contrib-julialint

**Comment by tonyhffong** [comment]
Done.
