### ISSUE TITLE
Spurious "not a container type" errors

### ISSUE THREAD

**Issue by sbromberger** [tonyhffong/Lint.jl#76]
```
function t2(n::Integer)
  δ = zeros(n)
  δ[1] = 5.4
  δ[2] = 6.7
  return δ
end
```
yields
```
linttest2.jl:3 [t2             ] ERROR  δ has apparent type Integer, not a container type.
linttest2.jl:3 [t2             ] ERROR  δ is of an immutable type Integer
linttest2.jl:4 [t2             ] ERROR  δ has apparent type Integer, not a container type.
linttest2.jl:4 [t2             ] ERROR  δ is of an immutable type Integer
```

(This was from master as I was testing out the fix for #75.)

**Comment by tonyhffong** [comment]
I guess the flood gate is starting to open: https://github.com/tonyhffong/Lint.jl/issues/27

Thanks for the report!

**Comment by sbromberger** [comment]
Is there a preferred method of reporting these (or perhaps even not reporting these)? I recently discovered Lint and am using it on my packages to make sure I haven't done anything silly. Happy to do whatever you'd like.

**Comment by tonyhffong** [comment]
This is fine. I know that static type prediction in Lint.jl, especially in the area of array types is quite incomplete. Keep them coming.

**Comment by tomaskrehlik** [comment]
````{julia}
function geomMean(a::Vector{Float64})
	return prod(a)^(1/(size(a))[1])
end
````
yields
````
... [geomMean       ] ERROR  size(a) has apparent type Int64, not a container type.
````

**Comment by tonyhffong** [comment]
Your code parses into (1 / ( size(a)[1] ) for the exponent, hence the lint error. It is correctly diagnosed.
