### ISSUE TITLE
Adapt to the new [ a, b ] non-concat behavior

### ISSUE THREAD

**Issue by tonyhffong** [tonyhffong/Lint.jl#81]
https://github.com/JuliaLang/julia/pull/8599

**Comment by TotalVerb** [comment]
I don't think there is anything actionable here, since Lint deals with this correctly.

**Comment by TotalVerb** [comment]
I stand corrected. We need to stop throwing a linter error in this case, because `[[1, 2], [3, 4]]` is now valid in 0.5+.
