### ISSUE TITLE
Spurious "ERROR  g is of an immutable type LightGraphs.AbstractGraph"

### ISSUE THREAD

**Issue by sbromberger** [tonyhffong/Lint.jl#84]
```
abstract AbstractGraph
...

function add_vertex!(g::AbstractGraph)
    n = length(vertices(g)) + 1
    g.vertices = 1:n
    return n
end
```

**Comment by tonyhffong** [comment]
related: https://github.com/tonyhffong/Lint.jl/issues/56

**Comment by sbromberger** [comment]
Thanks, @tonyhffong - I confess to not being proficient enough to recognize whether these issues I'm submitting are new.

**Comment by tonyhffong** [comment]
That's fine. I just need a way to cross-ref related issues.
