### ISSUE TITLE
"Use of undeclared symbol" when function definition uses global variable defined later

### ISSUE THREAD

**Issue by jiahao** [tonyhffong/Lint.jl#86]
```jl
foo() = x
x = 1
```

produces the error:

```
try.jl:1 [foo            ] ERROR  Use of undeclared symbol x
```

But this is perfectly fine since by the end of the file both `foo` and `x` have been defined before `foo()` is ever invoked.

This is a problem for linting larger files (I tried it on `Color.jl`), which define several global constants at the end of the file after a series of method definitions which use those constants.

**Comment by tonyhffong** [comment]
Yes, this requires a 2-pass process and it is a missing feature.
