### ISSUE TITLE
Variable args causes a MethodError

### ISSUE THREAD

**Issue by phobon** [tonyhffong/Lint.jl#92]
I was trying out Lint for the first time today but it looks like it's currently broken with 0.4.

```
julia> lintstr("f(args...) = length(args)")
ERROR: MethodError: `start` has no method matching start(::Type{Any})
 in append_any at essentials.jl:113
 in anonymous at /home/jdlangs/.julia/v0.4/Lint/src/functions.jl:205
 in lintfunction at /home/jdlangs/.julia/v0.4/Lint/src/functions.jl:222
 in lintexpr at /home/jdlangs/.julia/v0.4/Lint/src/Lint.jl:147
 in lintstr at /home/jdlangs/.julia/v0.4/Lint/src/Lint.jl:102
 in lintstr at /home/jdlangs/.julia/v0.4/Lint/src/Lint.jl:75
```

**Comment by phobon** [comment]
Ah, I see it's a problem with the change in Tuple types. Maybe sometime soon I can try putting a PR together to use `@compat` for them.

**Comment by tonyhffong** [comment]
thanks for the report. check the master and see if it works better for you.

**Comment by phobon** [comment]
Thanks for the fast update! It no longer crashes on any of my v0.4 code.
