### ISSUE TITLE
Variables that begin with `e` and scientific notation.

### ISSUE THREAD

**Issue by marcusps** [tonyhffong/Lint.jl#98]
Variables names beginning with `e` followed by some integer, combined with the use of Julia's `*`-less notation for multiplication, can easily lead to strange behavior since `3e120` will be interpreted as a literal, while the user may have intended `3*e120`.

Similarly, depending on how one is using `e` (Euler's number), one should be careful with since the results of `e-10`, `2e`, and `2e-10` could lead to similar surprises that may be hard to debug.

Although the benefits of the more compact `*`-less notation for multiplication far out weight the negatives of these corner cases, it would be very helpful if Lint.jl could flag the use of such variables, or the use of scientific notation for floats when these variables are in scope.

**Comment by tonyhffong** [comment]
by the time the expression hits Lint, 3e10 would have become the floating point literal, so it cannot distinguish one way vs the other. I'm afraid this issue would be one for the Julia parser internals.

**Comment by marcusps** [comment]
Ok, I'll add an issue to JuliaLang/julia
